[package]
name = "tea_app_core"
version = "0.1.0"
authors = ["luoluo yu <>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
